### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by alashkov83** [SergeySatskiy/codimension#455]
------ Unhandled exception report at 2018-10-02 16:33:59.235170
Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/codimension/flowui/scopeitems.py", line 500, in hoverEnterEvent
    self.__navBarUpdate(self.getCanvasTooltip())
  File "/usr/local/lib/python3.6/dist-packages/codimension/flowui/items.py", line 155, in getCanvasTooltip
    parts.insert(0, canvas.getScopeName())
  File "/usr/local/lib/python3.6/dist-packages/codimension/flowui/vcanvas.py", line 180, in getScopeName
    scopeToTheLeftName = cellToTheLeft.getScopeName()
  File "/usr/local/lib/python3.6/dist-packages/codimension/flowui/vcanvas.py", line 180, in getScopeName
    scopeToTheLeftName = cellToTheLeft.getScopeName()
  File "/usr/local/lib/python3.6/dist-packages/codimension/flowui/vcanvas.py", line 180, in getScopeName
    scopeToTheLeftName = cellToTheLeft.getScopeName()
  [Previous line repeated 9982 more times]
  File "/usr/local/lib/python3.6/dist-packages/codimension/flowui/vcanvas.py", line 164, in getScopeName
    for _, row in enumerate(self.cells):
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by SergeySatskiy** [comment]
Aleksandr,
could you please attach the source file which caused the problem?
My guess, the exception was generated when the mouse pointer was moved over the graphics pane, right?

**Comment by alashkov83** [comment]
Sergey,
right, and mouse scrolling the graphics pane. 
Source file:
[https://github.com/alashkov83/hydrocluster/blob/master/hydrocluster/cli.py](url)

**Comment by SergeySatskiy** [comment]
OK, thank you.
I will have a look. It is a morning here and I will try to look at it when I get home tonight. This is definitely a bug but that part of code has not been touched for a long time so I have no ETA when I fix it.
Thanks for submitting!

**Comment by SergeySatskiy** [comment]
The bug is fixed.
Release 4.3.1 includes the bug fix.

**Comment by alashkov83** [comment]
Good news!
Sincerely,
Alexander

ср, 3 окт. 2018 г., 5:10 Sergey Satskiy <notifications@github.com>:
